/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jikexueyuan_callandroidapi_JniBridge */

#ifndef _Included_com_jikexueyuan_callandroidapi_JniBridge
#define _Included_com_jikexueyuan_callandroidapi_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jikexueyuan_callandroidapi_JniBridge
 * Method:    showLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jikexueyuan_callandroidapi_JniBridge_showLog
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
